Project and proposal crud
sauce-community/dao pull request #18
Opened 2021-12-15 05:16 UTC by plutownium

2021-12-18 17:11 UTC, noahdahlman requested changes
It would be great if before we merged this we could get tests for each route, perhaps with https://jestjs.io/

2021-12-18 17:11 UTC, noahdahlman commented on api/models/Project.model.js
> +const { string } = require("hardhat/internal/core/params/argumentTypes");
Where is this used at?

2021-12-18 17:11 UTC, noahdahlman commented on api/models/Project.model.js
> +const { string } = require("hardhat/internal/core/params/argumentTypes");
Where is this used at?

2021-12-18 17:11 UTC, noahdahlman commented on api/models/Proposal.model.js
> +const { string } = require("hardhat/internal/core/params/argumentTypes");
`const { string } = require("hardhat/internal/core/params/argumentTypes");`
is unused

2021-12-18 17:11 UTC, noahdahlman commented on api/models/User.model.js
> +// export
Missing export?

2021-12-18 17:11 UTC, noahdahlman commented on api/projects/projects.js
> +  let projectId = req.query.id;
Should this be `req.params`?

2021-12-18 17:11 UTC, noahdahlman commented on api/projects/projects.js
> +  let projectId = req.query.id;
Should this be `req.params`?

2021-12-18 22:49 UTC, plutownium commented on api/models/Project.model.js
> +const { string } = require("hardhat/internal/core/params/argumentTypes");
Looks like nowhere. I do not recall importing that line. It can be removed.

2021-12-18 22:50 UTC, plutownium commented on api/projects/projects.js
> +  let projectId = req.query.id;
Yes. I'm still learning the difference between req.params and req.query. Good catch

2022-01-11 21:35 UTC, noahdahlman approved these changes

2022-01-11 21:35 UTC, merged